name: Develop - Deploy Frontend
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts'
    - run: npm install
    - name: Lint code
      run: |
        npm run lint

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts'
    - run: npm install
    - name: Run tests
      run: |
        npm run test

  docker-package:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
    - uses: actions/checkout@v4
    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: |
        docker build . -t ghcr.io/${{ github.repository }}:develop
    - name: Push Docker image to registry
      run: |
        docker push ghcr.io/${{ github.repository }}:develop

  deploy:
    runs-on: ubuntu-latest
    needs: docker-package
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEVELOP_SSH_SECRET }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ vars.DEVELOP_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Login to the GitHub Packages Docker Registry
        run: ssh ${{ vars.DEVELOP_SSH_USERNAME }}@${{ vars.DEVELOP_SSH_HOST }} "echo ${{ secrets.DOCKER_REGISTRY_TOKEN }} | docker login ghcr.io -u ${{ vars.DOCKER_REGISTRY_USER }}" --password-stdin

      - name: Run docker-compose
        run: ssh ${{ vars.DEVELOP_SSH_USERNAME }}@${{ vars.DEVELOP_SSH_HOST }} "cd frontend && docker compose up -d"

      - name: Delete unused images
        run: ssh ${{ vars.DEVELOP_SSH_USERNAME }}@${{ vars.DEVELOP_SSH_HOST }} "docker image prune -f"

      - name: Logout from the GitHub Packages Docker Registry
        run: ssh ${{ vars.DEVELOP_SSH_USERNAME }}@${{ vars.DEVELOP_SSH_HOST }} "docker logout ghcr.io"
